services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - WRF_DIR=/wrf
    volumes:
      - ./data:/app/data
      - /home/user/wrf_data/wrfprd:/something
    restart: unless-stopped